base_url = "https://semanticdata.github.io/zola-minimal/"
title = "Minimal"
description = "This repo is used to test new web elements. It is an amalgamation of code snippets, all weaved together by Zola."

compile_sass = true
build_search_index = false
generate_feed = false
minify_html = false

taxonomies = [
  { name = "categories", feed = true },
  { name = "tags", feed = true },
]

[markdown]
highlight_code = false
highlight_theme = "ayu-light"

[extra]
sidebar = [
  { name = "Links", urls = [
    { name = "Test", url = "test/" },
    { name = "Posts", url = "posts/" },
    { name = "Firefox", url = "posts/unlock-firefox-sidebar/" },
    { name = "Tags", url = "tags/" },
    { name = "#placeholder", url = "tags/placeholder/" },
  ] },
]
