# Site's URL. Please include trailing "/".
base_url = "https://example.com/"
default_language = "en"
# description = "minimal"

compile_sass = true
build_search_index = false
generate_feeds = false
minify_html = false

[markdown]
highlight_code = true
highlight_theme = "material-dark"
