# Site's URL. Please include trailing "/".
base_url = "https://semanticdata.github.io/zola-minimal/"
title = "Zola Minimal"
description = "Minimal is a Zola theme based on the Jekyll theme of the same name."

compile_sass = true
build_search_index = false
generate_feed = false
minify_html = false

[markdown]
highlight_code = true
# highlight_theme = "ayu-light"

[search]
include_title = true
include_description = false
include_path = false
include_content = true
index_format = "elasticlunr_javascript"

[extra]
author = "Miguel Pimentel" # Author's name
email = "contact@miguelpimentel.do" # Author's email
